### ISSUE TITLE
Issue when upload topology on Azure Storm Insight

### ISSUE THREAD

**Issue by Shriyanshmit** [Blackmist/eventhub-storm-hybrid#5] opened 2015-04-01 08:50 UTC
Hi,
When i upload toplogy on Azure Storm Insight got issue related to SCPHost.exe missing . I copied from local machine and copy to RDP at location C:\apps\dist\storm-0.9.3.2.2.1.0-2340\scp\apps.
I upload two topology EventHubReader & EventHubWriter.

I follow article https://github.com/Blackmist/eventhub-storm-hybrid/issues/4 but admin contains nothing.

Please let me know is there any other configuration required ?
Error:
java.lang.RuntimeException: Missing Application Host C:\apps\dist\storm-0.9.3.2.2.1.0-2340\scp\apps\SCPHost.exe
    at microsoft.scp.proxy.TaskHost.getWorkingDirectory(TaskHost.java:146) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.TaskHost.execute(TaskHost.java:184) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.TaskHost.checkAndExecute(TaskHost.java:176) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.ScpService.checkAndLaunchWorker(ScpService.java:93) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.storm.bolt.ScpNetBolt.prepare(ScpNetBolt.java:106) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at backtype.storm.daemon.executor$fn__5132$fn__5145.invoke(executor.clj:732) ~[storm-core-0.9.3.2.2.1.0-2340.jar:0.9.3.2.2.1.0-2340]
    at backtype.storm.util$async_loop$fn__550.invoke(util.clj:463) ~[storm-core-0.9.3.2.2.1.0-2340.jar:0.9.3.2.2.1.0-2340]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
2015-04-01 07:59:28 b.s.d.executor [ERROR] 
java.lang.RuntimeException: Missing Application Host C:\apps\dist\storm-0.9.3.2.2.1.0-2340\scp\apps\SCPHost.exe
    at microsoft.scp.proxy.TaskHost.getWorkingDirectory(TaskHost.java:146) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.TaskHost.execute(TaskHost.java:184) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.TaskHost.checkAndExecute(TaskHost.java:176) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.proxy.ScpService.checkAndLaunchWorker(ScpService.java:93) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at microsoft.scp.storm.bolt.ScpNetBolt.prepare(ScpNetBolt.java:106) ~[microsoft.scp-0.1.0-SNAPSHOT.jar:na]
    at backtype.storm.daemon.executor$fn__5132$fn__5145.invoke(executor.clj:732) ~[storm-core-0.9.3.2.2.1.0-2340.jar:0.9.3.2.2.1.0-2340]
    at backtype.storm.util$async_loop$fn__550.invoke(util.clj:463) ~[storm-core-0.9.3.2.2.1.0-2340.jar:0.9.3.2.2.1.0-2340]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]

![11](https://cloud.githubusercontent.com/assets/11751143/6939498/df2a912a-d88a-11e4-9604-f950f8d98a5b.PNG)
![image](https://cloud.githubusercontent.com/assets/11751143/6939524/15a4081c-d88b-11e4-921a-c65ebcdbe7a2.png)
![image](https://cloud.githubusercontent.com/assets/11751143/6939538/352b3ed0-d88b-11e4-8bdd-c42e3834bdf9.png)

Thanks

**Comment by Blackmist** [comment] 2015-04-02 20:03
Duplicate of #4, closing. Should have a fix uploaded later today.

**Closed as completed by Blackmist** 2015-04-02 20:03 UTC
Labels: duplicate
